language: csharp
solution: src/JiraTimeBot.sln

before_deploy: "zip -j JiraTimeBot.zip src/JiraTimeBot/bin/Release/*"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: JiraTimeBot.zip
  skip_cleanup: true
  on:
    tags: true